# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-16 23:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(1, 'Up'), (-1, 'Down')])),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_votes', to='music.Album')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_related_name': 'album_votes',
            },
        ),
        migrations.CreateModel(
            name='ArtistVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(1, 'Up'), (-1, 'Down')])),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_votes', to='music.Artist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_related_name': 'artist_votes',
            },
        ),
        migrations.CreateModel(
            name='PostVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(1, 'Up'), (-1, 'Down')])),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_votes', to='posts.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_related_name': 'post_votes',
            },
        ),
        migrations.CreateModel(
            name='SongVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(1, 'Up'), (-1, 'Down')])),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_votes', to='music.Song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_related_name': 'song_votes',
            },
        ),
        migrations.AlterUniqueTogether(
            name='songvote',
            unique_together=set([('song', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='postvote',
            unique_together=set([('post', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='artistvote',
            unique_together=set([('artist', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='albumvote',
            unique_together=set([('album', 'user')]),
        ),
    ]
