# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-28 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_desc',
            field=models.CharField(default='', max_length=250),
        ),
    ]
